# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "ahci" "xhci_pci" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/9a14bcf1-fb7d-4c1e-a8b6-cec5713d8730";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2538-3224";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/home/brian/GamesNVME" =
    { device = "/dev/disk/by-uuid/450b84ac-8abd-463e-8798-53a241cb5e6b";
      fsType = "btrfs";
    };

  fileSystems."/home/brian/.local/share/PrismLauncher" =
    { device = "/home/brian/GamesNVME/PrismLauncher";
      fsType = "none";
      options = [ "bind" ];
    };

  fileSystems."/home/brian/GamesSSD" =
    { device = "/dev/disk/by-uuid/30c0c1f7-dce4-4bf2-86d6-7e7d429780cb";
      fsType = "btrfs";
    };

  fileSystems."/home/brian/data" =
    { device = "/dev/disk/by-uuid/64c7d0c3-ed22-4f49-a24e-fda5dbd7d4db";
      fsType = "btrfs";
    };

  fileSystems."/home/brian/GamesHDD" =
    { device = "/dev/disk/by-uuid/0585d9ed-9042-4dbc-b3d5-e2e102a20401";
      fsType = "btrfs";
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-12566d3ea739.useDHCP = lib.mkDefault true;
  # networking.interfaces.docker0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp14s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.veth1190cb2.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp15s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
